FROM golang:1.13.8-alpine3.11

RUN apk update && apk add --no-cache git

WORKDIR /app

RUN git init && \
    go get github.com/dgrijalva/jwt-go && \
    go get github.com/nirasan/go-jwt-handler && \
    go get github.com/go-sql-driver/mysql && \
    go get github.com/jinzhu/gorm && \
    go get golang.org/x/xerrors
